### ISSUE TITLE
UTF-8 Support?

### ISSUE THREAD

**Issue by cibersheep** [erkyrath/remglk#31]
Playing [Afuera](http://iplayif.com/?story=http%3A//www.caad.es/incanus/Afuera.z5) or any other game with "special" character (à, é, ç, ñ, etc) shows a `??` character

Tested with remglk build against frotz, nitfol and bocfel

```
  { "line":6, "content":[{ "style":"normal", "text":"            Realizado por: Sebasti??n Armas (Incanus)              "}]},
  { "line":7, "content":[{ "style":"normal", "text":"            (C) A??o 2007                                          "}]},
```

Is it an init setting that I have to set?

**Comment by cibersheep** [comment]
Oh, it might be Frtoz "fault"?
https://gitlab.com/DavidGriffith/frotz/merge_requests/87

**Comment by erkyrath** [comment]
Everything going into and coming out of remglk should be UTF-8, because JSON always is. I've tested this with glulxe and unicodetest.ulx:

 {"id":21, "text": [
  {"append":true, "content":[{ "style":"input", "text":"x big"}]},
  {"content":[{ "style":"normal", "text":"This is all the signs in sequence:"}]},
  {},
  {"content":[{ "style":"normal", "text":"AEIOU with umlauts: ÄËÏÖÜ"}]},
  {"content":[{ "style":"normal", "text":"aeiou with umlauts: äëïöü"}]},
  {"content":[{ "style":"normal", "text":"At signs: @ @ @"}]},
  {"content":[{ "style":"normal", "text":"Greek: αβγδε (abgde)"}]},
  {"content":[{ "style":"normal", "text":"Hebrew: אבגדמ (abgdm... the aleph should be on the right)"}]},
  {"content":[{ "style":"normal", "text":"Punctuation: ‘single curly quotes’ “double curly quotes”"}]},
  {"content":[{ "style":"normal", "text":"Ligatures: æ (ae) œ (oe) ŋ (nj) ﬀ (ff) ﬁ (fi) ﬃ (ffi) ﬄ (ffl)"}]},
  {"content":[{ "style":"normal", "text":"Hirigana: おすも (O SU MO)"}]},
  {"content":[{ "style":"normal", "text":"Katakana: オスモ (O SU MO)"}]},
  {"content":[{ "style":"normal", "text":"Emoji: 😀🚀🚲🍄 (GRINNING FACE, ROCKET, BICYCLE, MUSHROOM)"}]},
  {},
  {"content":[{ "style":"normal", "text":">"}]}
 ] }

**Comment by cibersheep** [comment]
Thanks for the test. I didn't know that ulx test «game». It will become handy to narrow tje search. Thank you

**Comment by cibersheep** [comment]
Ay... Nope. That's how I read the json in the stdout... my fault. Sorry
