### ISSUE TITLE
gcc warning mktemp is dangerous

### ISSUE THREAD

**Issue by cibersheep** [erkyrath/remglk#37]
Hello.
When building some terps agains remglk, I get this warning from the compiler

```
remglk/libglk.a(rgfref.c.o): In function `glk_fileref_create_temp':
rgfref.c:(.text+0x51d): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
```

Is something we should take care of?
If so, how? Adding a variable or parameter for the builder? Or something else?

**Comment by curiousdannii** [comment]
Just yesterday I was pondering whether it was worth flagging the same thing for cheapglk!

**Comment by erkyrath** [comment]
The "dangerous" warning is because if two copies of the process are running, and they hit that line at exactly the same time, they could both accidentally wind up with the same filename. In theory. I can't think of a scenario where this would happen in real life.

In glkterm, DavidG contributed a patch which calls mkstemp(): https://github.com/erkyrath/glkterm/commit/228cbc12253dd3172ce4b130a92fa22f83dced8e

But I'm pretty sure that's wrong actually -- it leaks the returned file descriptor.

I *think* the "correct" patch is to call mkstemp() and then close the file descriptor. But I've never been sure enough to bother doing it when the risk is so remote.

**Comment by erkyrath** [comment]
Let's try what I think is the correct fix.

https://github.com/erkyrath/remglk/commit/e5e09027745e47926efc09ca9e990cb3a660812b
