### ISSUE TITLE
Doesn't handle numbers in scientific notation

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/remglk#47]
Parchment on mobile Chrome is producing this, which I think is not being parsed by Remglk, and causing the Emglken terps to crash: `"buffermarginy":7.105427357601002e-15`.

I'll see if I can find a solution on my end, but I'm also raising this as something you might want to look at, for full JSON compatiblility.

_Originally posted by @curiousdannii in https://github.com/erkyrath/remglk/issues/46#issuecomment-1207351986_

**Comment by erkyrath** [comment]
Gah, what a nuisance. And yes, remglk should be able to handle that even though it's a nuisance.

**Comment by erkyrath** [comment]
Take a look at branch https://github.com/erkyrath/remglk/tree/double-expo and see if that works?

Another change in this branch: where the library expects an integer, it will round to the nearest integer rather than towards zero. This does not effect `metrics` (where the library expects floats). But if you send a `gen` or `window` value of 9.9, it will now be rounded to 10.

**Comment by curiousdannii** [comment]
Ah thanks! I'll give it a try soon.

Hmm, I think the only situation in which rounding makes sense is for mouse event coordinates, to cover the case where someone forgot to round them. For the generation number I'd expect that to be an error. But it's also probably very unlikely to happen, and if it simplifies the code a lot to just automatically round them, then it's probably okay.

**Comment by curiousdannii** [comment]
Yep, that branch works perfectly, thanks!

**Comment by erkyrath** [comment]
Great.

We can't require a JSON-format spec to reject `10.0` when it expects `10`. JS can't distinguish those cases. JSON libraries in other languages may or may not, so yeah, it's simpler if this one doesn't.
